<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.luoke</groupId>
        <artifactId>roco-map-tracker</artifactId>
        <version>1.1.1</version>
    </parent>

    <artifactId>roco-ui</artifactId>
    <packaging>jar</packaging>

    <properties>
        <pgo.file>default.iprof</pgo.file>
    </properties>

    <dependencies>
        <dependency>
            <groupId>net.jcip</groupId>
            <artifactId>jcip-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>com.luoke</groupId>
            <artifactId>roco-engine</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-graphics</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-base</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.mkpaz</groupId>
            <artifactId>atlantafx-base</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>
                <configuration>
                    <mainClass>com.luoke.app.Main</mainClass>
                    <options>
                        <option>-Xmx384m</option>
                        <option>-Xms64m</option>
                        <option>-XX:MaxMetaspaceSize=96m</option>
                        <option>-XX:ReservedCodeCacheSize=96m</option>
                        <option>-XX:+UseSerialGC</option>
                        <option>-XX:MaxHeapFreeRatio=25</option>
                        <option>-XX:MinHeapFreeRatio=10</option>
                        <option>-Dprism.maxvram=134217728</option>
                        <option>--add-reads=javafx.graphics=ALL-UNNAMED</option>
                        <option>--enable-native-access=ALL-UNNAMED</option>
                    </options>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>com.luoke.app.Main</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>com.luoke.app.Main</mainClass>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                            <filters>
                                <filter>
                                    <artifact>com.microsoft.onnxruntime:onnxruntime</artifact>
                                    <excludes>
                                        <exclude>ai/onnxruntime/native/linux-*/**</exclude>
                                        <exclude>ai/onnxruntime/native/osx-*/**</exclude>
                                        <exclude>ai/onnxruntime/native/osx-*/**</exclude>
                                    </excludes>
                                </filter>
                                <!-- 排除不需要的元数据文件 -->
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/maven/**</exclude>
                                        <exclude>META-INF/NOTICE</exclude>
                                        <exclude>META-INF/LICENSE</exclude>
                                        <exclude>META-INF/README.md</exclude>
                                        <exclude>META-INF/*.txt</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>native</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>0.10.0</version>
                        <extensions>true</extensions>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>compile</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                        </executions>
                        <configuration>
                            <mainClass>com.luoke.app.Main</mainClass>
                            <imageName>RocoMapTracker</imageName>
                            <useArgFile>true</useArgFile>
                            <agent>
                                <enabled>false</enabled>
                                <options>
                                    <option>experimental-class-loader-support</option>
                                    <option>allow-incomplete-classpath</option>
                                </options>
                            </agent>
                            <buildArgs>
                                <!-- =====调试时需要将这两项注释掉，有些错误不会被记录在日志中====== -->
                                <!-- 指定链接器子系统为 WINDOWS -->
                                <buildArg>-H:NativeLinkerOption=/SUBSYSTEM:WINDOWS</buildArg>
                                <!-- 指定入口点，确保在无控制台模式下正确启动 -->
                                <buildArg>-H:NativeLinkerOption=/ENTRY:mainCRTStartup</buildArg>
                                <!-- ==================================================== -->
                                <buildArg>-R:MaxHeapSize=512M</buildArg>
                                <buildArg>-R:MinHeapSize=128M</buildArg>
                                <buildArg>-R:MaxDirectMemorySize=512M</buildArg>
                                <buildArg>-H:+StaticExecutableWithDynamicLibC</buildArg>
                                <buildArg>-H:+RemoveUnusedSymbols</buildArg>
                                <buildArg>-H:+UseCompressedReferences</buildArg>
                                <buildArg>-Dfile.encoding=UTF-8</buildArg>
                                <buildArg>--enable-native-access=ALL-UNNAMED</buildArg>
                                <buildArg>--no-fallback</buildArg>
                                <buildArg>-Djava.awt.headless=false</buildArg>
                                <buildArg>-H:+InstallExitHandlers</buildArg>
                                <buildArg>-Djdk.nio.maxCachedBufferSize=262144</buildArg>
                                <buildArg>-Djdk.virtualThread.carrierStackSize=2097152</buildArg>
                                <buildArg>-Os</buildArg>
                                <buildArg>-march=x86-64-v3</buildArg>
                                <buildArg>--initialize-at-run-time=com.sun.prism.**</buildArg>
                                <buildArg>--initialize-at-run-time=com.sun.glass.ui.**</buildArg>
                                <buildArg>--initialize-at-run-time=javafx.**</buildArg>
                                <buildArg>
                                    -H:IncludeResources=^(com/sun/prism/.*|com/sun/javafx/.*|dll/.*|sift/.*|capture/.*|update/.*|icon/.*|logback\.xml|extract-list\.txt)$
                                </buildArg>
                                <buildArg>-H:IncludeResourceBundles=ch.qos.logback.*</buildArg>
                                <buildArg>
                                    -H:ReachabilityMetadataResources=META-INF/native-image/reachability-metadata.json
                                </buildArg>
                                <buildArg>--add-exports=javafx.graphics/com.sun.prism.shader=ALL-UNNAMED</buildArg>
                                <buildArg>--add-exports=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED</buildArg>
                                <buildArg>--add-exports=javafx.graphics/com.sun.prism.d3d=ALL-UNNAMED</buildArg>
                                <buildArg>--emit build-report</buildArg>
                                <buildArg>-H:+ReportExceptionStackTraces</buildArg>
                                <buildArg>--enable-url-protocols=http,https</buildArg>
                                <buildArg>-H:+JNI</buildArg>
                                <buildArg>-H:NativeLinkerOption=${project.build.directory}/rmt.res</buildArg>
                                <buildArg>-H:+StripDebugInfo</buildArg>
                            </buildArgs>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.3.0</version>
                        <executions>
                            <execution>
                                <id>compile-icon-resource</id>
                                <phase>initialize</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>${session.executionRootDirectory}/compile_icon.bat</executable>
                                    <arguments>
                                        <argument>${project.build.directory}/rmt.res</argument>
                                        <argument>${project.basedir}/src/main/resources/icon/rmt.rc</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>native-instrument</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>0.10.0</version>
                        <extensions>true</extensions>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>compile</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                        </executions>
                        <configuration>
                            <mainClass>com.luoke.app.Main</mainClass>
                            <imageName>RocoMapTracker-instrumented</imageName>
                            <useArgFile>true</useArgFile>
                            <agent>
                                <enabled>false</enabled>
                                <options>
                                    <option>experimental-class-loader-support</option>
                                    <option>allow-incomplete-classpath</option>
                                </options>
                            </agent>
                            <buildArgs>
                                <buildArg>-R:MaxHeapSize=512M</buildArg>
                                <buildArg>-R:MinHeapSize=128M</buildArg>
                                <buildArg>-R:MaxDirectMemorySize=512M</buildArg>
                                <buildArg>--pgo-instrument</buildArg>
                                <buildArg>-J-Xmx24g</buildArg>
                                <buildArg>-march=x86-64-v3</buildArg>
                                <buildArg>-H:+UseCompressedReferences</buildArg>
                                <buildArg>-Dfile.encoding=UTF-8</buildArg>
                                <buildArg>--enable-native-access=ALL-UNNAMED</buildArg>
                                <buildArg>--no-fallback</buildArg>
                                <buildArg>-Djava.awt.headless=false</buildArg>
                                <buildArg>-H:+InstallExitHandlers</buildArg>
                                <buildArg>-Djdk.nio.maxCachedBufferSize=262144</buildArg>
                                <buildArg>-Djdk.virtualThread.carrierStackSize=2097152</buildArg>
                                <buildArg>-H:+JNI</buildArg>
                                <buildArg>-H:+ReportExceptionStackTraces</buildArg>
                                <buildArg>--enable-url-protocols=http,https</buildArg>
                                <buildArg>--initialize-at-run-time=com.sun.prism.**</buildArg>
                                <buildArg>--initialize-at-run-time=com.sun.glass.ui.**</buildArg>
                                <buildArg>--initialize-at-run-time=javafx.**</buildArg>
                                <buildArg>
                                    -H:IncludeResources=^(com/sun/prism/.*|com/sun/javafx/.*|dll/.*|sift/.*|capture/.*|update/.*|icon/.*|logback\.xml|extract-list\.txt)$
                                </buildArg>
                                <buildArg>-H:IncludeResourceBundles=ch.qos.logback.*</buildArg>
                                <buildArg>
                                    -H:ReachabilityMetadataResources=META-INF/native-image/reachability-metadata.json
                                </buildArg>
                                <buildArg>--add-exports=javafx.graphics/com.sun.prism.shader=ALL-UNNAMED</buildArg>
                                <buildArg>--add-exports=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED</buildArg>
                                <buildArg>--add-exports=javafx.graphics/com.sun.prism.d3d=ALL-UNNAMED</buildArg>
                            </buildArgs>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>native-pgo</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>0.10.0</version>
                        <extensions>true</extensions>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>compile</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                        </executions>
                        <configuration>
                            <mainClass>com.luoke.app.Main</mainClass>
                            <imageName>RocoMapTracker</imageName>
                            <useArgFile>true</useArgFile>
                            <agent>
                                <enabled>false</enabled>
                                <options>
                                    <option>experimental-class-loader-support</option>
                                    <option>allow-incomplete-classpath</option>
                                </options>
                            </agent>
                            <buildArgs>
                                <!-- =====调试时需要将这两项注释掉，有些错误不会被记录在日志中====== -->
                                <!-- 指定链接器子系统为 WINDOWS -->
                                <buildArg>-H:NativeLinkerOption=/SUBSYSTEM:WINDOWS</buildArg>
                                <!-- 指定入口点，确保在无控制台模式下正确启动 -->
                                <buildArg>-H:NativeLinkerOption=/ENTRY:mainCRTStartup</buildArg>
                                <!-- ==================================================== -->
                                <buildArg>-R:MaxHeapSize=512M</buildArg>
                                <buildArg>-R:MinHeapSize=128M</buildArg>
                                <buildArg>-R:MaxDirectMemorySize=512M</buildArg>
                                <buildArg>-H:+StaticExecutableWithDynamicLibC</buildArg>
                                <buildArg>-H:+RemoveUnusedSymbols</buildArg>
                                <buildArg>--pgo=${pgo.file}</buildArg>
                                <buildArg>-J-Xmx24g</buildArg>
                                <buildArg>-Os</buildArg>
                                <buildArg>-march=x86-64-v3</buildArg>
                                <buildArg>-H:+StripDebugInfo</buildArg>
                                <buildArg>-H:+UseCompressedReferences</buildArg>
                                <buildArg>-Dfile.encoding=UTF-8</buildArg>
                                <buildArg>--enable-native-access=ALL-UNNAMED</buildArg>
                                <buildArg>--no-fallback</buildArg>
                                <buildArg>-Djava.awt.headless=false</buildArg>
                                <buildArg>-H:+InstallExitHandlers</buildArg>
                                <buildArg>-Djdk.nio.maxCachedBufferSize=262144</buildArg>
                                <buildArg>-Djdk.virtualThread.carrierStackSize=2097152</buildArg>

                                <buildArg>-H:+JNI</buildArg>
                                <buildArg>-H:+ReportExceptionStackTraces</buildArg>
                                <buildArg>--enable-url-protocols=http,https</buildArg>
                                <buildArg>--initialize-at-run-time=com.sun.prism.**</buildArg>
                                <buildArg>--initialize-at-run-time=com.sun.glass.ui.**</buildArg>
                                <buildArg>--initialize-at-run-time=javafx.**</buildArg>
                                <buildArg>
                                    -H:IncludeResources=^(com/sun/prism/.*|com/sun/javafx/.*|dll/.*|sift/.*|capture/.*|update/.*|icon/.*|logback\.xml|extract-list\.txt)$
                                </buildArg>
                                <buildArg>-H:IncludeResourceBundles=ch.qos.logback.*</buildArg>
                                <buildArg>
                                    -H:ReachabilityMetadataResources=META-INF/native-image/reachability-metadata.json
                                </buildArg>
                                <buildArg>--add-exports=javafx.graphics/com.sun.prism.shader=ALL-UNNAMED</buildArg>
                                <buildArg>--add-exports=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED</buildArg>
                                <buildArg>--add-exports=javafx.graphics/com.sun.prism.d3d=ALL-UNNAMED</buildArg>
                                <buildArg>-H:NativeLinkerOption=${project.build.directory}/rmt.res</buildArg>
                            </buildArgs>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.3.0</version>
                        <executions>
                            <execution>
                                <id>compile-icon-resource</id>
                                <phase>initialize</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>${session.executionRootDirectory}/compile_icon.bat</executable>
                                    <arguments>
                                        <argument>${project.build.directory}/rmt.res</argument>
                                        <argument>${project.basedir}/src/main/resources/icon/rmt.rc</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
